data:
    image: ubuntu
    volumes:
        - /var/lib/mysql
        - /data/db
    command: /bin/true
mongodb:
    image: mongo
    ports: 
        - "27017:27017"
    volumes_from:
        - data
    command: "--smallfiles"
mysqldb:
    image: mysql:5.6.24
    ports: 
        - "3306:3306"
    volumes_from:
        - data
    environment:
       - MYSQL_DATABASE=orgstars
       - MYSQL_ROOT_PASSWORD=OrgStars27182818
ctlctr:
    image: gitorgstars/ctlctr-dev:3.20h
    ports:
        - "8000:8000"
        - "80:80"
    command: bash -c "python /src/code/manage.py runserver 0.0.0.0:8000"
    links:
        - mongodb
        - mysqldb
    environment:
        - MYSQL_HOST=mysqldb
        - MONGO_HOST=mongodb
        - TERM=xterm
    volumes: 
        - .:/src/code
        - build/dev/.ssh:/root/.ssh
